# -*- coding: utf-8 -*-
"""reverse_string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N-ZWVKia4O8MMVcZjIg4LzKGpn_jbD7m
"""

sample_str = "1234abcd"
j=''
for i in sample_str[::-1]:
  j += i
print(j)